version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - '5432:5432'
    volumes:
    - db:/var/lib/postgresql/data

  web:
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000" 
volumes:
  db:
    driver: local

  

