version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SECRET_KEY=${SECRET_KEY}
        - DEBUG=${DEBUG}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

