# Generated by Django 4.0.5 on 2022-08-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0004_alter_address_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adress', 'verbose_name_plural': 'Adresses'},
        ),
    ]
