# Generated by Django 4.0.5 on 2022-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0005_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='letting',
            name='URL',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
