# Generated by Django 4.0.5 on 2022-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0006_letting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='letting',
            name='type',
            field=models.CharField(default='', max_length=25),
        ),
    ]
