version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  docker: circleci/docker@2.1.3
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv env 
            source env/bin/activate 
            pip install -r requirements.txt
      - run:
          name: Lint
          command:
            flake8
      - run: 
          command: 
            source env/bin/activate
            pytest

    build-deploy-docker:
      docker:
        - image: cimg/python:3.10.2
          auth:
            username: e1m2i3l4
            password: $DOCKERHUB_ACCESS_TOKEN
      machine: true
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build and push Docker image to Heroku
            command: |
              docker login --username=$DOCKER_USERNAME --password-stdin=$DOCKERHUB_ACCESS_TOKEN
              docker build -t $CIRCLE_SHA1 .
              docker tag $CIRCLE_SHA1 . $DOCKER_USERNAME/oclettingsite:$CIRCLE_SHA1
              docker push $DOCKER_USERNAME/oclettingsite:$CIRCLE_SHA1
              
    deploy-heroku:
      executor: heroku/default
      steps:
        - checkout
        - run:
            name: Storing previous commit
            command: |
              git rev-parse HEAD > ./commit.txt
        - heroku/install
        - setup_remote_docker
        - run:
            name: Pushing to heroku registry
            command: |
              heroku container:login
              heroku create $HEROKU_APP_NAME
              heroku container:push web -a=$HEROKU_APP_NAME
              heroku container:release -a $HEROKU_APP_NAME web
              heroku open -a=$HEROKU_APP_NAME         

workflows:
  build_test_and_deploy:
    jobs:
      - build-and-test
      - build-deploy-docker:
          filters:
            branches:
              only: 
                - master
          requires:
            - build-and-test
      - deploy-heroku:
          requires:
            - build-deploy-docker
            