version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  docker: circleci/docker@2.1.3
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2


    steps:
      - checkout
      - run:
          command: |
            python -m venv venv 
            ./venv/Srcipts/activate 
            python pip install -r requirements.txt
      - run: 
          command: python -m pytest


          
  # test:
  #   steps:
  #     - checkout
  #     - run:
  #         name: Runing tests
  #         command: |
  #           .venv/bin/activate
  #           python -m pytest
  #     - store_test_results:
  #         path: test-results
  #     - store_artifacts:
  #         path: test-results

  # linting:
  #   executor: default
  #   steps:
  #     - checkout
  #     - restore_cache_cmd
  #     - run:
  #       name: Runing linting
  #       command: |
  #         .venv\Script\activate
  #         flake8

  # build_test_deploy:
  #   jobs:
  #     - build      
  #     - test:
  #         requires:
  #           - build
  #     # - linting:
  #     #     requires:
  #     #       - build                           
  #         filters:
  #           branches:
  #             only: master    







    # jobs:
    #   - build-and-test
    #   - docker/publish:
    #       image: "e1m2i3l4/orange_county_lettings"
    #       tag: "$latest"
    #       extra_build_args: '--build-arg secret_key=$SECRET_KEY'
    #       requires:
    #         - build-and-test
    #       filters:
    #         branches:
    #           only: master
    #   - heroku/deploy-via-git:
    #       requires:
    #         - build-and-test
    #       filters:
    #         branches:
    #           only: master