version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  docker: circleci/docker@2.1.3
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_ACCESS_TOKEN
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
          
workflows:
  test-and-deploy:
    jobs:
      - build-and-test
      - docker/publish:
          image: "e1m2i3l4/orange_county_lettings"
          tag: "$latest"
          extra_build_args: '--build-arg secret_key=$SECRET_KEY'
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: master